.struct REG
                .org    $02
  .union
  r0            .word
  .struct
  r0L           .byte
  r0H           .byte
  .endstruct
  .endunion
  .union
  r1            .word
  .struct
  r1L           .byte
  r1H           .byte
  .endstruct
  .endunion
  .union
  r2            .word
  .struct
  r2L           .byte
  r2H           .byte
  .endstruct
  .endunion
  .union
  r3            .word
  .struct
  r3L           .byte
  r3H           .byte
  .endstruct
  .endunion
  .union
  r4            .word
  .struct
  r4L           .byte
  r4H           .byte
  .endstruct
  .endunion
  .union
  r5            .word
  .struct
  r5L           .byte
  r5H           .byte
  .endstruct
  .endunion
  .union
  r6            .word
  .struct
  r6L           .byte
  r6H           .byte
  .endstruct
  .endunion
  .union
  r7            .word
  .struct
  r7L           .byte
  r7H           .byte
  .endstruct
  .endunion
  .union
  t0            .word
  .struct
  t0L           .byte
  t0H           .byte
  .endstruct
  .endunion
  .union
  t1            .word
  .struct
  t1L           .byte
  t1H           .byte
  .endstruct
  .endunion
  .union
  t2           .word
  .struct
  t2L          .byte
  t2H          .byte
  .endstruct
  .endunion
  .union
  t3           .word
  .struct
  t3L          .byte
  t3H          .byte
  .endstruct
  .endunion
  .union
  t4           .word
  .struct
  t4L          .byte
  t4H          .byte
  .endstruct
  .endunion
  .union
  t5           .word
  .struct
  t5L          .byte
  t5H          .byte
  .endstruct
  .endunion
  .union
  t6           .word
  .struct
  t6L          .byte
  t6H          .byte
  .endstruct
  .endunion
  .union
  t7           .word
  .struct
  t7L          .byte
  t7H          .byte
  .endstruct
  .endunion
.endstruct